// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// vecLeven_C
int vecLeven_C(CharacterVector s, CharacterVector t);
RcppExport SEXP _hood2net_vecLeven_C(SEXP sSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(vecLeven_C(s, t));
    return rcpp_result_gen;
END_RCPP
}
// vecSub_C
int vecSub_C(CharacterVector s, CharacterVector t);
RcppExport SEXP _hood2net_vecSub_C(SEXP sSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(vecSub_C(s, t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hood2net_vecLeven_C", (DL_FUNC) &_hood2net_vecLeven_C, 2},
    {"_hood2net_vecSub_C", (DL_FUNC) &_hood2net_vecSub_C, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hood2net(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
