#' Returns the neighborhood size (i.e., degree) for all or a subset of nodes in the language network.
#'
#' @param network An `igraph` network object, generated by `make_network()` or `make_network_sep()` functions.
#' @param node_name A vector containing node names to obtain values for. Node names must be found in `igraph::V(network)$name`. If unspecified, the default is to return values for all nodes in the network.
#'
#' @returns A named numeric vector.
#' @export
#'
#' @examples
#' # Use the demo data for executing examples
#'
#'   test <- make_network(sample1)
#'   get_neighbor_size(network = test) # all nodes
#'   get_neighbor_size(network = test, node_name = "1_cat") # for 1 node
#'
get_neighbor_size <- function(network, node_name = NULL) {

  # sanity checks

  # node_name in network?
  if(!is.null(node_name)) { # execute this check only if node_name is not null
    if(!all(node_name %in% igraph::V(network)$name)) {
      stop('Message: node name(s) not found in network.')
    }
  }

  if(is.null(node_name)) { # default is ALL nodes

    result <- igraph::degree(network)

  } else {

    result <- igraph::degree(network, v = node_name)

  }

  return(result)

}
