#' Returns a summary of global network characteristics of the language network.
#'
#' @param network An `igraph` network object, generated by `make_network()` or `make_network_sep()` functions.
#'
#' @returns A named vector of global network metrics. For more information about these metrics, refer to the package vignette.
#' @export
#'
#' @examples
#' #' # Use the demo data for executing examples
#'
#'   test <- make_network(sample1)
#'   get_network_info(network = test)
#'
get_network_info <- function(network) {

  # is the object an igraph object?
  if(!igraph::is_igraph(network)) {
    stop('Message: The object is not an igraph object')
  }

  # does the network have undirected and unweighted edges?
  if(igraph::is_directed(network)) {
    stop('Message: The network has directed edges.')
  }
  if(igraph::is_weighted(network)) {
    stop('Message: The network has weighted edges.')
  }

  # network metrics
  V <- igraph::gorder(network) # no. of nodes
  E <- igraph::gsize(network) # no. of edges

  ASPL <- igraph::mean_distance(network, directed = F) # average shortest path length
  CC1 <- igraph::transitivity(network, type = 'global') # global clustering coefficient
  CC2 <- igraph::transitivity(network, type = 'local', isolates = 'zero') |> mean() # average clustering coefficient
  diameter <- igraph::diameter(network, directed = F)

  mean_k <- igraph::degree(network) |> mean() # average degree

  ncomp <- igraph::components(network)$no

  # proportion in largest component
  lcc_prop <- max(igraph::components(network)$csize)/sum(igraph::components(network)$csize)

  results <- c(V, E, ASPL, CC1, CC2, diameter, mean_k, ncomp, lcc_prop) |> round(3)

  names(results) <- c('nodes', 'edges', 'ASPL', 'global CC', 'mean CC', 'diameter', 'mean degree', 'no. components', 'prop. in LCC')

  return(results)
}
