#' Returns the mean of a neighborhood's attribute for all or a subset of nodes in the language network.
#'
#' @param network An `igraph` network object, generated by `make_network()` or `make_network_sep()` functions.
#' @param node_name A vector containing node names to obtain values for. Node names must be found in `igraph::V(network)$name`. If unspecified, the default is to return values for all nodes in the network.
#' @param attribute A string stating the node attribute to obtain the mean values for. The attribute must be found in `igraph::vertex_attr_names(network)`. Typically it will be one of the node attribute columns in the `item_df` data frame object used to create the network.
#'
#' @returns A named numeric vector.
#' @export
#'
#' @examples
#' # Use the demo data for executing examples
#'
#'   test <- make_network(sample1)
#'   get_neighbor_mean(network = test, attribute = "length") # all nodes
#'   get_neighbor_mean(network = test, node_name = "cat", attribute = "length") # for 1 node
#'
get_neighbor_mean <- function(network, node_name = NULL, attribute) {

  # sanity checks

  # node_name in network?
  if(!is.null(node_name)) { # execute this check only if node_name is not null
    if(!all(node_name %in% igraph::V(network)$name)) {
      stop('Message: node name(s) not found in network.')
    }
  }

  # attribute is in network vertex attribute list?
  if(!attribute %in% igraph::vertex_attr_names(network)) {
    stop('Message: node attribute not found in network.')
  }

  # attribute is a numeric variable that can be summed
  if(!is.numeric(igraph::vertex_attr(network, attribute))) {
    stop('Message: node attribute is not numeric.')
  }

  if(is.null(node_name)) { # default is ALL nodes

    result <- sapply(igraph::V(network)$name, function(x) {

    igraph::vertex_attr(network, attribute, igraph::ego(network, nodes = x, mindist = 1)[[1]]) |> mean()

    })

  } else {

    result <- sapply(node_name, function(x) {

    igraph::vertex_attr(network, attribute, igraph::ego(network, nodes = x, mindist = 1)[[1]]) |> mean()

    })

  }

  return(result)

}
