# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecLeven_C <- function(s, t) {
    .Call(`_hood2net_vecLeven_C`, s, t)
}

vecSub_C <- function(s, t) {
    .Call(`_hood2net_vecSub_C`, s, t)
}

